const PLACE_TYPE_MAP: Record<string, { zh: string; en: string }> = {
  parking: { zh: "停車場", en: "Parking" },
  house: { zh: "住宅", en: "House" },
  service: { zh: "服務設施", en: "Service" },
  restaurant: { zh: "餐廳", en: "Restaurant" },
  cafe: { zh: "咖啡廳", en: "Café" },
  school: { zh: "學校", en: "School" },
  hospital: { zh: "醫院", en: "Hospital" },
  pharmacy: { zh: "藥局", en: "Pharmacy" },
  bank: { zh: "銀行", en: "Bank" },
  supermarket: { zh: "超市", en: "Supermarket" },
  convenience: { zh: "便利商店", en: "Convenience Store" },
  bus_stop: { zh: "公車站", en: "Bus Stop" },
  station: { zh: "車站", en: "Station" },
  subway: { zh: "捷運站", en: "Subway" },
  park: { zh: "公園", en: "Park" },
  toilets: { zh: "公共廁所", en: "Public Restroom" },
  hotel: { zh: "旅館", en: "Hotel" },
  shop: { zh: "商店", en: "Shop" },
  office: { zh: "辦公室", en: "Office" },
  apartments: { zh: "公寓", en: "Apartments" },
  residential: { zh: "住宅區", en: "Residential" },
  commercial: { zh: "商業區", en: "Commercial" },
  industrial: { zh: "工業區", en: "Industrial" },
  temple: { zh: "寺廟", en: "Temple" },
  church: { zh: "教堂", en: "Church" },
  library: { zh: "圖書館", en: "Library" },
  museum: { zh: "博物館", en: "Museum" },
  cinema: { zh: "電影院", en: "Cinema" },
  fuel: { zh: "加油站", en: "Gas Station" },
  post_office: { zh: "郵局", en: "Post Office" },
  police: { zh: "警察局", en: "Police" },
  fire_station: { zh: "消防局", en: "Fire Station" },
  clinic: { zh: "診所", en: "Clinic" },
  dentist: { zh: "牙醫", en: "Dentist" },
  kindergarten: { zh: "幼兒園", en: "Kindergarten" },
  university: { zh: "大學", en: "University" },
  college: { zh: "學院", en: "College" },
  marketplace: { zh: "市場", en: "Marketplace" },
  sports_centre: { zh: "運動中心", en: "Sports Center" },
  swimming_pool: { zh: "游泳池", en: "Swimming Pool" },
  playground: { zh: "遊樂場", en: "Playground" },
  yes: { zh: "建築", en: "Building" },
};

export function getPlaceTypeLabel(type: string, lang: string): string {
  const entry = PLACE_TYPE_MAP[type];
  if (entry) return lang === "en" ? entry.en : entry.zh;
  return type.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
