export type GeoPoint = { type: "Point"; coordinates: [number, number] };
export type SlimOsmA11y = { osmId: string; name?: string; category: "wheelchair_accessible"|"kerb_cut"|"ramp"|"elevator"|"toilet"; wheelchair?: "yes"|"limited"|"no"; tags?: Record<string, string>; location: GeoPoint };
export type OsmA11y = SlimOsmA11y & { importedAt: string };
export type WaitInfo = { time: number|string|null; source: "realtime"|"schedule"|"unavailable" };
export type NearestBus = { plateNumb: string; position: [number, number]; speed?: number; stopsAway?: number };
export type ExitInfo = { exitName: string; exitNumber: string; type: "elevator"|"ramp"; coords: [number, number] };
export type WalkLeg = { type: "WALK"; from: string; to: string; distanceM: number; minutesEst: number; polyline: [number, number][]; a11yFacilities: SlimOsmA11y[]; a11yRefs?: string[]; exitInfo?: ExitInfo | null };
export type BusLeg = { type: "BUS"; routeName: string; departureStop: string; arrivalStop: string; departureStopId?: string; arrivalStopId?: string; cityCode?: string; departureTime?: string; arrivalTime?: string; waitInfo: WaitInfo; estimatedWaitMinutes: number; direction: 0 | 1; polyline: [number, number][]; departureStopA11y: SlimOsmA11y[]; arrivalStopA11y: SlimOsmA11y[]; nearestBus?: NearestBus; a11yRefs?: string[] };
export type MetroLeg = { type: "METRO"; railSystem: string; lineId: string; lineName: string; lineUid: string; departureStation: string; arrivalStation: string; departureStationUid: string; arrivalStationUid: string; direction: 0 | 1; stopsCount: number; rideMinutes: number; departureTime?: string; arrivalTime?: string; waitInfo: WaitInfo; estimatedWaitMinutes: number; polyline: [number, number][]; departureStationA11y: SlimOsmA11y[]; arrivalStationA11y: SlimOsmA11y[]; facilityHighlights: string[]; a11yRefs?: string[] };
export type ThsrLeg = { type: "THSR"; trainNo: string; departureStation: string; arrivalStation: string; departureStationUID: string; arrivalStationUID: string; departureTime: string; arrivalTime: string; rideMinutes: number; waitInfo: WaitInfo; estimatedWaitMinutes: number; polyline: [number, number][]; departureStationA11y: SlimOsmA11y[]; arrivalStationA11y: SlimOsmA11y[]; facilityHighlights: string[]; a11yRefs?: string[] };
export type TraLeg = { type: "TRA"; trainNo: string; trainTypeName: string; departureStation: string; arrivalStation: string; departureStationUID: string; arrivalStationUID: string; departureTime: string; arrivalTime: string; rideMinutes: number; waitInfo: WaitInfo; estimatedWaitMinutes: number; polyline: [number, number][]; departureStationA11y: SlimOsmA11y[]; arrivalStationA11y: SlimOsmA11y[]; facilityHighlights: string[]; a11yRefs?: string[] };
export type RouteLeg = WalkLeg | BusLeg | MetroLeg | ThsrLeg | TraLeg;
export type ScoreComponents = { facilityScore: number; timeScore: number; criticalFeatureScore: number };
export type AccessibleRoute = { routeId: string; routeName: string; totalMinutes: number; transferCount: number; legs: RouteLeg[]; accessibilityHighlights: string[]; accessibilityScore?: number; accessibilityLabel?: "excellent"|"good"|"fair"|"poor"|"critical"; scoreComponents?: ScoreComponents; facilities?: Record<string, SlimOsmA11y> };
export type RouteIntent = { from: string; to: string; mode: "wheelchair"|"elderly"|"visual_impaired"|"normal"; departureTime: string; preferences: { minimizeTransfers: boolean; preferElevator: boolean } };
export type AccessibleRouteData = { origin: { lat: number; lng: number }; destination: { lat: number; lng: number }; city: string; routes: AccessibleRoute[]; intent?: RouteIntent };
export type RouteExplanation = { summary: string; accessibilityHighlights: string[]; warnings: string[]; alternatives: string | null };
export type AirQualityLevel = "GOOD"|"MODERATE"|"UNHEALTHY_SENSITIVE"|"UNHEALTHY"|"VERY_UNHEALTHY"|"HAZARDOUS"|"";
export type AirQuality = { description: string; quality: AirQualityLevel };
export const isWalkLeg = (l: RouteLeg): l is WalkLeg => l.type === "WALK";
export const isBusLeg = (l: RouteLeg): l is BusLeg => l.type === "BUS";
export const isMetroLeg = (l: RouteLeg): l is MetroLeg => l.type === "METRO";
export const isThsrLeg = (l: RouteLeg): l is ThsrLeg => l.type === "THSR";
export const isTraLeg = (l: RouteLeg): l is TraLeg => l.type === "TRA";
